### ISSUE TITLE
Ex/Import: Bottom buttons invisible in dark theme

### ISSUE THREAD

**Issue by uli-on** [NobodyForNothing/blood-pressure-monitor-fl#73] opened 2023-06-26 12:50 UTC
**What happened**
The background colour of the bottom buttons remains white in the dark theme while their text colour is already white,  which makes them impossible to spot as buttons .

**Comment by NobodyForNothing** [comment] 2023-06-26 14:24
duplicate of #71

**Closed by NobodyForNothing** 2023-06-26 14:24 UTC
