### ISSUE TITLE
Settings with switches aren't saved through app restarts

### ISSUE THREAD

**Issue by uli-on** [NobodyForNothing/blood-pressure-monitor-fl#342] opened 2024-07-04 12:58 UTC
It's always on, resulting in a permanent "Bluetooth disabled" banner above the input fields. v1.7.0

**Comment by NobodyForNothing** [comment] 2024-07-04 13:08
Hi, thanks for the report. Unfortunately I cannot reproduce this.

To clarify:

1. you disabled this switch:
![image](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/82763757/56aaf120-0314-4c99-80dc-3bf49120c05f)

2. Bluetooth input is shown regardless:
![image](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/82763757/44fe92f2-47e0-4d29-8220-3d81c39f17b6)

Could you export the settings that cause this?

**Comment by uli-on** [comment] 2024-07-04 14:02
It remembers the switch position during the same session. But as soon as I eg. swipe Bpm out of the app switcher and the look at the Bluetooth setting the switch is always on. (Apologies for not answering your questions exactly and without screenshots, I'm in a hurry)

**Comment by NobodyForNothing** [comment] 2024-07-04 14:26
Thank you for taking the time to respond, you answered exactly what I needed to know.

I still can't reproduce your issue, although it helped catch another problem with resetting this setting when deleting settings (bcde09dd04de8a1942e61bea2106f3c28455cd85). I will investigate your issue further on other devices/installation sources. Do you still have the Fairphone 3 with the app from F-Droid?

**Comment by NobodyForNothing** [comment] 2024-07-04 14:39
It should be fine without :)

**Comment by uli-on** [comment] 2024-07-04 19:10
Not much effort with the DevStat app:

```
Screen Metrics
Width: 1080 px
Height: 2022 px
Display density: 460 dpi
Drawable density: Unknown DPI: 460
Screen size: Normal

Software
Android version: 13
SDK Int: 33
OpenGL ES version: 3.2
Google Play Services version: 24.23.34 (190400-645140581) [242334038]
Build Number: 6.A.029.0

Hardware
Manufacturer: Fairphone
Device model: FP3
Device: FP3
Brand: Fairphone
Board: FP3
Host: jenkins-agent-01
Product: FP3
Memory class: 192 MB
Large memory class: 512 MB
Max memory: 192 MB
Free space: 35,3 GB
Telephony: Enabled
SD Card: Present: true, Emulated: true
ABIs: arm64-v8a, armeabi-v7a, armeabi
Online Processors: 8
```

**Comment by uli-on** [comment] 2024-07-04 20:05
> Could you export the settings that cause this?

Would it help to send you my settings db?

**Comment by NobodyForNothing** [comment] 2024-07-04 20:16
That's what I meant, yes.

**Comment by uli-on** [comment] 2024-07-04 20:46
For whatever reason I've had to zip it in order to upload it. Yet it seems not to be attached to this post. :/

**Comment by uli-on** [comment] 2024-07-04 20:57
You've got mail

**Comment by NobodyForNothing** [comment] 2024-07-05 08:14
Curiously your settings are still in v1.6.4 format. even the app version number update isn't updated (this is one of the first things that happen on app launch). 

I'm also getting very interesting results freshly installing the f-droid build on a real device: The add measurement button doesn't work (although for me the settings saved).

#344 also showed some results that shouldn't have occurred from the code alone and are not reproducible on an emulator. To me this feels like either an bug in the f-droid build script or in flutter.

**Comment by NobodyForNothing** [comment] 2024-07-05 14:09
I think I found and fixed the issue. Since there has been quite a few issues with this release I will publish a new release.

**Comment by NobodyForNothing** [comment] 2024-07-05 14:13
I still couldn't reproduce the issue myself, so please give me feedback once f-droid builds.

**Comment by uli-on** [comment] 2024-07-05 20:09
> please give me feedback once f-droid builds.
> 
Will do. Thanks!

**Comment by uli-on** [comment] 2024-07-06 16:12
Out if curiosity: is your fix aimed at switch positions in general? The reason why I'm asking is, my "Compact measurement list" switch position isn't saved across app restarts as well.

**Comment by NobodyForNothing** [comment] 2024-07-06 17:07
@uli-on the fix is aimed at all settings in general. It appears like your settings file doesn't write changes at all (I hardened the auto-save setup logic). 

Thinking about this again: Do measurements save between restarts? If not this might be some problem on your end (SD-card issues, [others](https://www.google.com/search?q=fairphone+(not+OR+error)+(save+OR+store))).

**Comment by uli-on** [comment] 2024-07-06 17:31
> Do measurements save between restarts?

Thankfulky they do. Phew! :)

**Comment by uli-on** [comment] 2024-07-06 17:46
Thanks for the link, I click/read through several pages from there and found that I currently do have the most current build for my device.

**Comment by uli-on** [comment] 2024-07-09 11:59
The F-Droid build was delivered today. The compact view issue (#341) is solved, thanks! The forgetful switches issue is not, sorry. But the "sticky" position for compact view is my favourite (compact on) and I can live with the Bluetooth banner on top of the measurement form. Yet I (have to ) hope there won't be more switches added to the prefs 😄)

**Comment by Der-Flip** [comment] 2024-07-12 21:05
I don't like jumping into this closed issue but I don't really wanna open a new one for now, as you are already aware:

Every restart of the app, it resets to the modern/ new layout here as well on two devices, one storing on sd and f-droid build, one storing on internal and Google play, both running android 10.

**Comment by NobodyForNothing** [comment] 2024-07-12 21:38
Don't worry about the issue being closed. Is this only true for switches or do other settings(time format, color) also fail to save?

**Comment by Der-Flip** [comment] 2024-07-12 22:05
Tested with time format (first item in settings) and yes, it also fails to save

Because you mentioned it above: new entries are being saved / stored reliably.

**Comment by kp8888** [comment] 2024-08-10 22:56
I'm facing the same issue. Using Android 11 and v1.7.2 of the application. The switches reset to the previous value after closing the app. Measurement info saves normally.

Please let me know if there's any other information I can provide. Thank you.

**Comment by NobodyForNothing** [comment] 2024-08-27 08:54
@uli-on @Der-Flip @kp8888 Can someone who experiences this issue install the app from the [relaible-settings](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/tree/342-reliable-settings) branch and check whether the issue is fixed?

Please note that this *WILL* **DELETE** ALL EXISTING APP DATA. So please **make BACKUPS**!
After reading the disclaimer: `cd app && flutter run`

I can provide apk builds, please email me about them, since I don't want them to be mistaken for real releases in the wild, as they are also going to **delete** your data.

**Closed** 2024-09-01 16:48 UTC
Labels: bug, can't reproduce

**Comment by Der-Flip** [comment] 2024-09-03 18:10
Hi, sorry I didn't get back to you. I wanted to test it but I couldn't find the time. First vacation, I returned from last week and now I have some family health stuff to deal with. Is the testing still necessary or has it been shipped already? If it still needs testing I will try to find a quiet minute this week, though.
